apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: firefly-iii
  name: firefly-iii
  namespace: finance-manager
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: firefly-iii
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: firefly-iii
        tier: frontend
    spec:
      containers:
      - env:
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              key: app_key
              name: firefly-iii-secrets-86ctbcmk29
        - name: DB_HOST
          value: firefly-iii-mysql
        - name: DB_CONNECTION
          value: mysql
        - name: DB_DATABASE
          value: fireflyiii
        - name: DB_USERNAME
          value: root
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: db_password
              name: firefly-iii-secrets-86ctbcmk29
        - name: TRUSTED_PROXIES
          value: '**'
        image: gcr.io/builder-budget-app/finance-manager:ea786a
        imagePullPolicy: Always
        name: firefly-iii
        ports:
        - containerPort: 8080
          name: firefly-iii
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/www/html/storage/upload
          name: firefly-iii-upload
        - mountPath: /var/www/html/.env
          name: dotenv
          subPath: .env
      volumes:
      - name: firefly-iii-upload
        persistentVolumeClaim:
          claimName: firefly-iii-upload-claim
      - configMap:
          defaultMode: 420
          name: dotenv
        name: dotenv
