apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: finance-manager-mysql-data
spec:
   storageClassName: standard
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 20Gi